name: Wait for Response Action
description:
    Checks a URL and expects a response within a defined time and with a defined
    status.
author: schwarzland.de

inputs:
    url:
        description: The URL to be checked
        required: true
        default: 'https://www.google.com'

    method:
        description:
            Allowed methods are GET, POST, PUT, PATCH, DELETE, HEAD, OPTIONS
        required: false
        default: 'GET'

    headers:
        description: Request Headers in JSON-Format
        required: false
        default: ''

    body:
        description: Body of the Request
        required: false
        default: ''

    body-reading-method:
        description:
            Specifies how the response body should be interpreted. Possible
            values are json, text
        required: false
        default: 'JSON'

    http-status:
        description: The expected http status
        required: false
        default: '200'

    timeout:
        description:
            The timeout (at least 500 milliseconds) determines when the entire
            query should be aborted..
        required: false
        default: '5000'

    single-fetch-timeout:
        description:
            The timeout (at least 200 milliseconds) determines when the single
            fetch should be aborted.
        required: false
        default: '1000'

    waiting-time:
        description:
            The waiting time (at least 200 milliseconds) after a fetch if the
            desired status has not yet been reached.
        required: false
        default: '1000'

outputs:
    duration:
        description: The time it took to complete the request.

    http-status:
        description: HTTP-Status

    response:
        description: The service's response

    result:
        description: query result (ok, timeout, maxLoop)

runs:
    using: node20
    main: dist/index.js
