name: Wait for Response Action
description:
  Checks a URL and expects a response within a defined time and with a defined
  status.
author: schwarzland.de

inputs:
  url:
    description: The URL to be checked
    required: true

  desired-method:
    description:
      Allowed methods are GET, POST, PUT, PATCH, DELETE, HEAD, OPTIONS
    required: false
    default: 'GET'

  request-headers:
    description: Request Headers in JSON-Format
    required: false
    default: ''

  expected-http-status:
    description: The expected http status
    required: false
    default: '200'

  interval:
    description:
      The interval (milliseconds) determines how often the URL should be
      checked.
    required: false
    default: '1000'

  timeout:
    description:
      The timeout (milliseconds) determines when the check should be aborted.
    required: false
    default: '5000'

  abort-at-timeout:
    description:
      Should the action be aborted on timeout (true), or should it continue
      running (false)
    required: false
    default: 'true'

outputs:
  time:
    description: The time until the desired status was reached.

  timeout-reached:
    description: Boolean, the timeout was reached (true).

  desired-status:
    description: Boolean, the desired status has been reached (true).

  response:
    description: The service's response

runs:
  using: node20
  main: dist/index.js
