name: Example Workflow

on:
  workflow_dispatch:
    inputs:
      url:
        description: The URL to be checked
        required: true
        default: 'google.com'
        type: string

      expected-http-status:
        description: The expected http status
        required: false
        default: '200'
        type: string

      interval:
        description:
          The interval (milliseconds) determines how often the URL should be
          checked.
        required: false
        default: '1000'
        type: string

      timeout:
        description:
          The timeout (seconds) determines when the check should be aborted.
        required: false
        default: '30'
        type: string

      abort-at-timeout:
        description:
          Should the action be aborted on timeout (true), or should it continue
          running (false)
        required: false
        default: 'true'
        type: string

permissions:
  actions: read
  contents: read

jobs:
  say-hello:
    name: Say Hello
    runs-on: ubuntu-latest

    steps:
      # Change @main to a specific commit SHA or version tag, e.g.:
      # actions/hello-world-javascript-action@e76147da8e5c81eaf017dede5645551d4b94427b
      # actions/hello-world-javascript-action@v1.2.3
      - name: Wait for Response
        id: waitForResponse
        uses: actions/wait-for-response-action@main
        with:
          url: ${{ inputs.url }}
          expected-http-status: ${{ inputs.expected-http-status }}
          interval: ${{ inputs.interval }}
          timeout: ${{ inputs.timeout }}
          abort-at-timeout: ${{ inputs.abort-at-timeout }}

      - name: Print Output
        id: output
        run: |
          echo "${{ steps.waitForResponse.outputs.time }}"
          echo "${{ steps.waitForResponse.outputs.timeout }}"
          echo "${{ steps.waitForResponse.outputs.desired-status }}"
